name: Mirror Source Repository

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:         # Allows manual triggering

jobs:
  update_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest commit hash from source repository
        id: get_source_commit
        run: |
          SOURCE_HASH=$(git ls-remote https://github.com/yonasuriv/PanicSonda.git HEAD | awk '{ print $1 }')
          echo "::set-output name=source_hash::$SOURCE_HASH"

      - name: Get last synced commit hash
        id: get_last_commit
        run: |
          if [ -f .last_source_commit ]; then
            LAST_HASH=$(cat .last_source_commit)
            echo "::set-output name=last_hash::$LAST_HASH"
          else
            echo "::set-output name=last_hash::"
          fi

      - name: Decide whether to update
        id: decide_update
        run: |
          if [ "${{ steps.get_source_commit.outputs.source_hash }}" != "${{ steps steps.get_last_commit.outputs.last_hash }}" ]; then
            echo "update_needed=true" >> $GITHUB_ENV
          else
            echo "update_needed=false" >> $GITHUB_ENV
          fi

      - name: Update repository with source contents
        if: env.update_needed == 'true'
        run: |
          git clone --depth 1 https://github.com/yonasuriv/PanicSonda.git temp_source
          rsync -a --delete temp_source/ . --exclude '.git' --exclude '.github' --exclude '.last_source_commit'
          rm -rf temp_source
          echo "${{ steps.get_source_commit.outputs.source_hash }}" > .last_source_commit

      - name: Commit and push changes
        if: env.update_needed == 'true'
        run: |
          git add .
          git commit -m "Mirror update from source repository"
          git push origin HEAD

      - name: No update needed
        if: env.update_needed == 'false'
        run: echo "No update needed."
