name: Mirror Source Repository

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:         # Allows manual triggering

jobs:
  update_repository:
    runs-on: ubuntu-latest

    steps:
    -:

    - name: Checkout this repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for accurate change detection

    -

    - name: Set up Git

      run: |
        git config config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Clone the source repository
      run: |
        git clone --depth 1 https://github.com/repo/url temp_source

    - name: Remove existing files
      run: |
        # Remove all files except the .git directory
        find . -maxdepth 1 ! -name '.git' ! -name '.' -exec rm -rf {} +

    - name: Copy files from source to root
      run: |
        # Copy copy all files from temp_source to current directory
        cp -a temp_source/. .
        # Remove the cloned source repository directory
        rm -rf temp_source

    - name: Check for changes
      id: check_changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_ENV
        else
          echo "changes=false" >> $GITHUB_ENV
        fi

    - name: Commit and push changes
      if: env.changes == 'true'
      run: |
        git add .
        git commit -m "Mirror update from source repository"
        git push origin HEAD

    - name: No changes detected
      if: env.changes == 'false'
      run: |
        echo "No changes detected. No action needed."
