name: Update Submodule

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:  # Allows you to manually trigger this workflow

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: true  # Fetch submodules
        fetch-depth: 0     # Fetch all history so we can check for changes

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch latest changes for submodules
      run: |
        git submodule update --remote --force --recursive
        git fetch --all

    - name: Debug submodule status
      run: |
        git submodule status
        git submodule foreach 'git status'
        git submodule foreach 'git log -1 --oneline'

    - name: Commit and push updates if any
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected in submodule, committing..."
          git add .
          git commit -m "Auto-update submodule to latest commit"
          git push origin HEAD
        else
          echo "No changes in submodule."
        fi