name: Mirror Source Repository

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate change detection

      - name: Set up Git
        run: |
          git configconfig --global user.name "github-actions[bot]"
          git configconfig --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest commit hash from source repository
        id: get_source_commit
        run: |
          echo "Fetching latest commit hash from source repository..."
          SOURCE_HASH=$(git ls-remote https://github.com/yonasuriv/PanicSonda.git HEAD | awk '{ print $1 }')
          echo "Latest source commit hash: $SOURCE_HASH"
          echo "source_hash=$SOURCE_HASH" >> $GITHUB_OUTPUT

      - name: Get last synced commit hash
        id: get_last_commit
        run: |
          if [ -f .last_source_commit ]; then
            LAST_HASH=$(cat .last_source_commit)
            echo "Last synced commit found: $LAST_HASH"
            echo "last_hash=$LAST_HASH" >> $GITHUB_OUTPUT
          else
            echo "No last synced commit found."
            echo "last_hash=" >> $GITHUB_OUTPUT
          fi

      - name: Decide whether to update
        id: decide_update
        env:
          SOURCE_HASH: ${{ steps.get_source_commit.outputs.source_hash }}
          LAST_HASH: ${{ steps.get_last_commit.outputs.last_hash }}
        run: |
          if [ "$SOURCE_HASH" != "$LAST_HASH" ] && [ -n "$SOURCE_HASH" ]; then
            echo "New commit detected. Proceeding to update."
            echo "update_needed=true" >> $GITHUB_ENV
          else
            echo "No new commits or unable to fetch source hash. Skipping update."
            echo "update_needed=false" >> $GITHUB_ENV
          fi

      - name: Checkout source repository
        if: env.update_needed == 'true'
        uses: actions/checkout@v3
        with:
          repository: yonasuriv/PanicSonda
          path: temp_source
          ref: main  # Replace with the branch you want to clone
          # If the source repository is private, provide a token:
          token: ${{ secrets.SOURCE_REPO_TOKEN }}

      - name: List contents of temp_source
        if: env.update_needed == 'true'
        run: |
          echo "Contents of temp_source:"
          ls -la temp_source

      - name: Update repository with source contents
        if: env.update_needed == 'true'
        env:
          SOURCE_HASH: ${{ steps.get_source_commit.outputs.source_hash }}
        run: |
          set -e
          if [ -d "temp_source" ] && [ "$(ls -A temp_source)" ]; then
            echo "Removing old files..."
            find . -maxdepth 1 ! -name '.git' ! -name '.' ! -name '.github' -exec rm -rf {} +
            echo "Copying new files..."
            cp -a temp_source/. .
            rm -rf temp_source
            echo "$SOURCE_HASH" > .last_source_commit
          else
            echo "Error: 'temp_source' directory does not exist or is empty."
            exit 1
          fi

      - name: Commit and push changes
        if: env.update_needed == 'true'
        run: |
          git add .
          git commit -m "Mirror update from source repository"
          git push origin HEAD

      - name: No update needed
        if: env.update_needed == 'false'
        run: |
          echo "No update needed."
